services:  
  django_admin:
    hostname: authenticationservice
    build:
      context: ./portfolio_django_admin
      dockerfile: Dockerfile
    container_name: myportfolio-djangoadmin
    command: uv run python -m debugpy --listen 0.0.0.0:4000 manage.py runserver 0.0.0.0:${DJANGO_ADMIN_LOCAL_PORT:-8000} --noreload
    volumes:
      - ./portfolio_django_admin/src:/usr/local/app/src
    ports:
      - "${DJANGO_ADMIN_HOST_PORT:-8000}:${DJANGO_ADMIN_LOCAL_PORT:-8000}"
      - 3000:4000

    env_file:
      - ./.env

    networks:
      - platform_net
   
networks:
  platform_net:
    driver: bridge
    name: my-portfolio-network
    external: true