services:  
  django_admin:
    hostname: authenticationservice
    build:
      context: ./portfolio_django_admin
      dockerfile: Dockerfile
    container_name: myportfolio-djangoadmin
    command: uv run uvicorn portfolio_django_admin.asgi:application --host 0.0.0.0 --port ${DJANGO_ADMIN_LOCAL_PORT:-8000} --reload
    volumes:
      - ./portfolio_django_admin/src:/usr/local/app/src
    ports:
      - "${DJANGO_ADMIN_HOST_PORT:-8000}:${DJANGO_ADMIN_LOCAL_PORT:-8000}"

    networks:
      - platform_net

    env_file:
      - ./.env

networks:
  platform_net:
    driver: bridge
    name: my-portfolio-network
    external: true