version: "3.8"

services:  
  django_admin:
    build: .
    container_name: myportfolio-djangoadmin
    command: daphne -b 0.0.0.0 -p ${DJANGO_ADMIN_LOCAL_PORT} portfolio_django_admin.asgi:application
    volumes:
      - ./app:/app
    ports:
      - "${DJANGO_ADMIN_HOST_PORT}:${DJANGO_ADMIN_LOCAL_PORT}"
      - 3000:4000

    networks:
      - platform_net

    restart: "always"

    environment:
      - POSTGRES_DB=${DJANGO_ADMIN_DB_NAME}
      - POSTGRES_USER=${DJANGO_ADMIN_DB_USER}
      - POSTGRES_PASSWORD=${DJANGO_ADMIN_DB_PASSWORD}
      - POSTGRES_HOST=${DJANGO_ADMIN_DB_HOST}
      - POSTGRES_PORT=${DJANGO_ADMIN_DB_PORT}

      - DEBUG=False
      - SECRET_KEY=${DJANGO_ADMIN_SERVICE_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ADMIN_SERVICE_ALLOWED_HOSTS}
      - TRUSTED_ORIGINS=${DJANGO_ADMIN_CSRF_TRUSTED_ORIGIN}

      - GITHUB_PAT=${GITHUB_PAT}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}

      - JWT_SECRET_KEY=${DJANGO_JWT_SECRET_KEY}
      - JWT_REFRESH_SECRET_KEY=${DJANGO_JWT_REFRESH_SECRET_KEY}
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=${DJANGO_JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
      - DEVICE_TOKEN_KEY=${DJANGO_DEVICE_TOKEN_KEY}
      - DEVICE_TOKEN_EXPIRATION=${DJANGO_DEVICE_TOKEN_EXPIRATION}
networks:
  platform_net:
    driver: bridge
    name: my-portfolio-network
    external: true