services:  
  django_admin:
    hostname: authenticationservice
    build:
      context: ./portfolio_django_admin
      dockerfile: Dockerfile
    container_name: myportfolio-djangoadmin
    command: uv run daphne -b 0.0.0.0 -p ${DJANGO_ADMIN_LOCAL_PORT:-8000} portfolio_django_admin.asgi:application
    volumes:
      - ./portfolio_django_admin/src:/usr/local/app/src
    ports:
      - "${DJANGO_ADMIN_HOST_PORT:-8000}:${DJANGO_ADMIN_LOCAL_PORT:-8000}"

    networks:
      - platform_net
    restart: "always"
    env_file: "./.env"

  celery_worker:
    build:
      context: ./portfolio_django_admin
      dockerfile: Dockerfile
    hostname: celeryworker
    container_name: celery-worker
    env_file:
      - ./.env
    networks:
      - platform_net
    volumes:
      - ./portfolio_django_admin/src:/usr/local/app/src
    command: uv run celery -A portfolio_django_admin.celery worker --loglevel=info

networks:
  platform_net:
    driver: bridge
    name: my-portfolio-network
    external: true