# Generated by Django 5.1 on 2026-04-14 02:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.EmailField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('trial', 'TRIAL'), ('deleted', 'DELETED')], db_index=True, default='active', max_length=20)),
                ('last_due_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_payment_due_date', models.DateTimeField(blank=True, null=True)),
                ('last_paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_paid_currency', models.CharField(blank=True, choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('INR', 'INR')], max_length=10, null=True)),
                ('last_paid_at', models.DateTimeField(blank=True, null=True)),
                ('last_payment_method', models.CharField(blank=True, choices=[('credit_card', 'CREDIT_CARD'), ('bank_transfer', 'BANK_TRANSFER'), ('credits', 'CREDITS')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'organizations',
            },
        )
    ]
