# Generated by Django 5.1 on 2026-04-15 16:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'ADMIN'), ('owner', 'OWNER'), ('manager', 'MANAGER'), ('editor', 'EDITOR'), ('viewer', 'VIEWER')], default='viewer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.EmailField(blank=True, max_length=255, null=True)),
                ('invitation_status', models.CharField(choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('declined', 'DECLINED')], db_index=True, default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invitation_token', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('invitation_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_users', to='organization.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organization_users',
                'unique_together': {('organization', 'user')},
            },
        ),
    ]
