# Generated by Django 5.1 on 2026-04-14 03:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationuser',
            name='invitation_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('declined', 'DECLINED')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='invitation_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='invitation_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='invited_by',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
