# Generated by Django 5.1 on 2026-04-18 16:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organization_updated_by_organizationuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('device_type', models.CharField(choices=[('Desktop', 'DESKTOP')], default='Desktop', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='organization.organization')),
            ],
            options={
                'db_table': 'devices',
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DeviceConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_type', models.CharField(choices=[('user_access', 'USER_ACCESS'), ('cpu_and_memory_usage', 'CPU_AND_MEMORY_USAGE'), ('io_device_usage', 'IO_DEVICE_USAGE')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='organization.device')),
            ],
            options={
                'db_table': 'device_configurations',
                'unique_together': {('device', 'data_type')},
            },
        ),
    ]
