# Generated by Django 5.1 on 2026-04-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_device_deviceconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='api_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='os_type',
            field=models.CharField(blank=True, choices=[('Windows', 'WINDOWS'), ('Ubuntu', 'UBUNTU')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='os_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='script_downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='script_downloaded_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
