# Generated by Django 5.1 on 2026-04-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_device_api_key_device_os_type_device_os_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='os_type',
            field=models.CharField(choices=[('Windows', 'WINDOWS'), ('Ubuntu', 'UBUNTU')], default='Ubuntu', max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='os_version',
            field=models.CharField(choices=[('10', 'WINDOWS_10'), ('24', 'UBUNTU_24')], default='24', max_length=50),
        ),
    ]
