# Generated by Django 5.1 on 2026-04-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_device_os_type_alter_device_os_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='os_version',
            field=models.CharField(choices=[('10', 'WINDOWS_10'), ('11', 'WINDOWS_11'), ('24', 'UBUNTU_24'), ('22', 'UBUNTU_22')], default='24', max_length=50),
        ),
    ]
