# Generated by Django 5.1 on 2026-05-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_device_os_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_upload_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
