# Generated by Django 5.1 on 2026-06-07 13:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis_services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='content',
        ),
        migrations.CreateModel(
            name='ServiceContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='jarvis_services.service')),
            ],
            options={
                'db_table': 'service_contents',
            },
        ),
    ]
