# Generated by Django 5.1 on 2026-06-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis_services', '0002_remove_service_content_servicecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecontent',
            name='sequence_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
