# Generated by Django 5.1 on 2026-06-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jarvis_services", "0003_servicecontent_sequence_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="sequence_number",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
