# Generated by Django 5.1 on 2024-11-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostSynchronizationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('progress', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('message', models.TextField(default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Post Synchronization Progress',
                'verbose_name_plural': 'Post Synchronization Progress',
                'ordering': ['created_at'],
            },
        ),
    ]
