# Generated by Django 5.1 on 2024-11-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsynchronizationprogress',
            name='total',
        ),
        migrations.AlterField(
            model_name='postsynchronizationprogress',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
